// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesIgnis.Models;

namespace RazorPagesIgnis.Migrations.Ignis
{
    [DbContext(typeof(IgnisContext))]
    partial class IgnisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("RazorPagesIgnis.Administrador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contrasena");

                    b.Property<string>("Correo");

                    b.Property<string>("Nombre");

                    b.Property<bool>("Status");

                    b.HasKey("ID");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("RazorPagesIgnis.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contrasena");

                    b.Property<string>("Correo");

                    b.Property<string>("Nombre");

                    b.Property<bool>("Status");

                    b.HasKey("ID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("RazorPagesIgnis.Proyecto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClienteID");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.Property<bool>("Status");

                    b.HasKey("ID");

                    b.HasIndex("ClienteID");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("RazorPagesIgnis.Rol", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RazorPagesIgnis.Solicitud", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CostoSolicitud");

                    b.Property<int>("HorasContratadas");

                    b.Property<int>("ModoDeContrato");

                    b.Property<string>("NivelExperiencia");

                    b.Property<string>("Observaciones");

                    b.Property<int?>("ProyectoID");

                    b.Property<string>("RolRequerido");

                    b.Property<bool>("Status");

                    b.Property<int?>("TecnicoAsignadoID");

                    b.HasKey("ID");

                    b.HasIndex("ProyectoID");

                    b.HasIndex("TecnicoAsignadoID");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("RazorPagesIgnis.Tecnico", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contrasena");

                    b.Property<string>("Correo");

                    b.Property<int>("Edad");

                    b.Property<string>("Nivel_experiencia");

                    b.Property<string>("Nombre");

                    b.Property<string>("Presentacion");

                    b.Property<bool>("Status");

                    b.HasKey("ID");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("RazorPagesIgnis.TecnicoSolicitud", b =>
                {
                    b.Property<int>("tecnicoID");

                    b.Property<int>("solicitudID");

                    b.HasKey("tecnicoID", "solicitudID");

                    b.HasAlternateKey("solicitudID", "tecnicoID");

                    b.ToTable("TecnicoSolicitud");
                });

            modelBuilder.Entity("RazorPagesIgnis.Proyecto", b =>
                {
                    b.HasOne("RazorPagesIgnis.Cliente")
                        .WithMany("ListaProyectos")
                        .HasForeignKey("ClienteID");
                });

            modelBuilder.Entity("RazorPagesIgnis.Solicitud", b =>
                {
                    b.HasOne("RazorPagesIgnis.Proyecto")
                        .WithMany("ListaDeSolicitudes")
                        .HasForeignKey("ProyectoID");

                    b.HasOne("RazorPagesIgnis.Tecnico", "TecnicoAsignado")
                        .WithMany()
                        .HasForeignKey("TecnicoAsignadoID");
                });

            modelBuilder.Entity("RazorPagesIgnis.TecnicoSolicitud", b =>
                {
                    b.HasOne("RazorPagesIgnis.Solicitud", "Solicitud")
                        .WithMany()
                        .HasForeignKey("solicitudID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RazorPagesIgnis.Tecnico", "Tecnico")
                        .WithMany("TecnicoSolicitudes")
                        .HasForeignKey("tecnicoID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
